FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements-training.txt ./requirements-training.txt
RUN python -m pip install --no-cache-dir -r requirements-training.txt
COPY train_model.py ./train_model.py
COPY predict_model.py ./predict_model.py
COPY prepare_dataset.py ./prepare_dataset.py
COPY generate_mock_data.py ./generate_mock_data.py

CMD ["python", "train_model.py"]
